### ISSUE TITLE
Demo fails

### ISSUE THREAD

**Issue by jkstyle2** [embodied-generalist/embodied-generalist#28]
Is the demo not available for now?

![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/39e51a53-319a-40e2-880d-3b27daa1a805)

**Comment by huangjy-pku** [comment]
Thanks for raising this. We have fixed it and you can try again.

**Comment by jkstyle2** [comment]
It still fails as below.

![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/94515dcc-6d9b-4c88-92cf-fdebfb5b52ef)
![image](https://github.com/embodied-generalist/embodied-generalist/assets/34189274/a605ba30-a2dc-43bd-a588-4f6ea2609f51)
